platform :ios, '9.3'
use_frameworks!

target 'ImageCollectionExpander' do
  pod 'AFNetworking'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'SwiftFSM'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'FLEX', '~> 2.0', :configurations => ['Debug']
end
